# Generated by Django 4.1.1 on 2022-09-11 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campertype', models.CharField(choices=[('AMITY', 'Amity Camper'), ('ANTHONY', 'Anthony Camper')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.DateTimeField()),
                ('dropoff', models.DateTimeField()),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.camper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
